### ISSUE TITLE
Add fallback for non-macOS

### ISSUE THREAD

**Issue by pfitzseb** [silvestreh/ui-theme#1]
Could add a setting for providing a background image that would then be appropriately blurred.

If you're feeling fancy you could also imitate true transparency with javascript: Get the window position (via `atom.windowDimensions`) and shift the background image appropriately. The rendering side of this should be pretty fast since it can be done via `transform`.

**Comment by silvestreh** [comment]
Implemented in 591ac416d46e29c3a39b310c5ef494c511381329
